<?php   
$tabla="";
$tabla.="<table class='table table-light table-sm'>";
$tabla.="<thead class='thead-dark'>";
$tabla.="<tr>";
$tabla.="<th><i class='fas fa-user-plus'></i> 1er Nivel</th>";
$tabla.="<th><i class='fas fa-user-plus'></i> 2do Nivel</th>";
$tabla.="<th><i class='fas fa-user-plus'></i> 3er Nivel</th>";
$tabla.="<th><i class='fas fa-user-plus'></i> 4to Nivel</th>";
$tabla.="<th><i class='fas fa-user-plus'></i> 5to Nivel</th>";
$tabla.="</tr>";
$tabla.="</thead>";
$tabla.="<tbody>";
$tabla.="<tr>";
$tabla.="<td>COMUNICACIÓN ORAL Y ESCRITA</td>";
$tabla.="<td>AUDITORÍA INFORMATICA</td>";
$tabla.="<td>ÉTICA PROFESIONAL</td>";
$tabla.="<td>APLICACIONES WEB II</td>";
$tabla.="<td>INTEGRACIÓN DE SISTEMAS INFORMATICOS</td>";
$tabla.="</tr>";
$tabla.="<tr>";
$tabla.="<td>COMUNICACIÓN ORAL Y ESCRITA</td>";
$tabla.="<td>AUDITORÍA INFORMATICA</td>";
$tabla.="<td>ÉTICA PROFESIONAL</td>";
$tabla.="<td>APLICACIONES WEB II</td>";
$tabla.="<td>INTEGRACIÓN DE SISTEMAS INFORMATICOS</td>";
$tabla.="</tr>";
$tabla.="<tr>";
$tabla.="<td>COMUNICACIÓN ORAL Y ESCRITA</td>";
$tabla.="<td>AUDITORÍA INFORMATICA</td>";
$tabla.="<td>ÉTICA PROFESIONAL</td>";
$tabla.="<td>APLICACIONES WEB II</td>";
$tabla.="<td>INTEGRACIÓN DE SISTEMAS INFORMATICOS</td>";
$tabla.="</tr>";
$tabla.="<tr>";
$tabla.="<td>COMUNICACIÓN ORAL Y ESCRITA</td>";
$tabla.="<td>AUDITORÍA INFORMATICA</td>";
$tabla.="<td>ÉTICA PROFESIONAL</td>";
$tabla.="<td>APLICACIONES WEB II</td>";
$tabla.="<td>INTEGRACIÓN DE SISTEMAS INFORMATICOS</td>";
$tabla.="</tr>";
$tabla.="<tr>";
$tabla.="<td>COMUNICACIÓN ORAL Y ESCRITA</td>";
$tabla.="<td>AUDITORÍA INFORMATICA</td>";
$tabla.="<td>ÉTICA PROFESIONAL</td>";
$tabla.="<td>APLICACIONES WEB II</td>";
$tabla.="<td>INTEGRACIÓN DE SISTEMAS INFORMATICOS</td>";
$tabla.="</tr>";
$tabla.="</tbody>";
$tabla.="</table>";

$tablad="";
$tablad = "<table class='table table-light table-sm''>";
$tablad .= "<thead class='thead-dark'>";
$tablad .= "<tr>";
$tablad .= "<th>Docente</th>";
$tablad .= "<th>Email</th>";
$tablad .= "</tr>";
$tablad .= "</thead>";
$tablad .= "<tbody>";
$tablad .= "<tr>";
$tablad .= "<td>David Galarza</td>";
$tablad .= "<td>dgalarza@itsqmet.edu.ec</td>";
$tablad .= "</tr>";
$tablad .= "<tr>";
$tablad .= "<td>Diego Ortega</td>";
$tablad .= "<td>dortega@itsqmet.edu.ec</td>";
$tablad .= "</tr>";
$tablad .= "<tr>";
$tablad .= "<td>Gabriela Rivas</td>";
$tablad .= "<td>grivas@itsqmet.edu.ec</td>";
$tablad .= "</tr>";
$tablad .= "<tr>";
$tablad .= "<td>Ing. Luis Yulan</td>";
$tablad .= "<td>lyulan@itsqmet.edu.ec</td>";
$tablad .= "</tr>";
$tablad .= "<tr>";
$tablad .= "<td>Alexis Taco</td>";
$tablad .= "<td>ataco@itsqmet.edu.ec</td>";
$tablad .= "</tr>";
$tablad .= "<tr>";
$tablad .= "<td>Viviana Flores</td>";
$tablad .= "<td>vflores@itsqmet.edu.ec</td>";
$tablad .= "</tr>";
$tablad .= "</tbody>";
$tablad .= "</table>";

header("Location: ../Vista/Principal_v.php?desarrollo=$tabla&docente=$tablad");


?>
